name: Nix Build

# Controls when the workflow will run
on:
  # # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src.llvm.llvm
          display-name: "Intel Open Source DPC++ Compiler"

  oneapi-src:
    runs-on: ubuntu-latest
    needs: llvm
    strategy:
      matrix:
        component: [oneDNN, oneMath]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src.${{ matrix.component }}
          display-name: ${{ matrix.component }}

  khronos-sycl-cts:
    runs-on: ubuntu-latest
    needs: llvm
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src.khronos-sycl-cts
          display-name: Khronos SYCL Conformance Test Suite

  ggml:
    runs-on: ubuntu-latest
    needs: oneapi-src
    strategy:
      matrix:
        component: [ggml, whisper-cpp, llama-cpp]
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/nix-build
        with:
          component: src.${{ matrix.component }}
          display-name: ${{ matrix.component }}
