name: "Nix Build Component"
description: "Build a Nix component and upload artifacts"
inputs:
  component:
    description: "Component name (e.g., src.llvm, src.oneDNN, etc.)"
    required: true
  display-name:
    description: "Display name for the build step (defaults to component name)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: git checkout
      uses: actions/checkout@v3
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        fail-mode: true
    - name: Build ${{ inputs.display-name || inputs.component }}
      shell: bash
      run: nix build --print-build-logs .#${{ inputs.component }}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ inputs.component }}-build-result
        path: result/
