name: "Nix Build Component"
description: "Build a Nix component and upload artifacts"
inputs:
  component:
    description: "Component name (e.g., src.llvm, src.oneDNN, etc.)"
    required: true
  display-name:
    description: "Display name for the build step (defaults to component name)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Check Nixpkgs inputs
      uses: DeterminateSystems/flake-checker-action@main
      with:
        fail-mode: false

    # - uses: cachix/install-nix-action@v25
    #   with:
    #     nix_path: nixpkgs=channel:nixos-unstable
    # - uses: cachix/cachix-action@v14
    #   with:
    #     name: blenderfreaky-intel-llvm
    #     authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

    - name: Build ${{ inputs.display-name || inputs.component }}
      shell: bash
      if: ${{ inputs.free == true }}
      run: nix build --print-build-logs .#${{ inputs.component }}

    - name: Build ${{ inputs.display-name || inputs.component }}
      shell: bash
      if: ${{ inputs.free == false }}
      env:
        NIXPKGS_ALLOW_UNFREE: 1
      run: nix build --impure --print-build-logs .#${{ inputs.component }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ inputs.component }}-build-result
        path: result/
